# Generated by Django 2.2.10 on 2021-07-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('catagory', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_code', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=100)),
                ('purchase_rate', models.BigIntegerField()),
                ('mrp_rate', models.BigIntegerField()),
                ('wholesale_rate', models.BigIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Company')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Category')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Dealer_Details',
            fields=[
                ('dealer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Category')),
            ],
        ),
    ]
