# Generated by Django 2.2.10 on 2021-07-21 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Sale',
            fields=[
                ('bill_no', models.AutoField(primary_key=True, serialize=False)),
                ('billing_date', models.DateField(auto_now=True)),
                ('Product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Product')),
                ('customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Customers')),
                ('type_of_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.Sale_Type')),
            ],
        ),
    ]
